// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ceffo/toast"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAlertSpec creates a new instance of MockAlertSpec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertSpec(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertSpec {
	mock := &MockAlertSpec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAlertSpec is an autogenerated mock type for the AlertSpec type
type MockAlertSpec struct {
	mock.Mock
}

type MockAlertSpec_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlertSpec) EXPECT() *MockAlertSpec_Expecter {
	return &MockAlertSpec_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockAlertSpec
func (_mock *MockAlertSpec) Resolve(fontStyle toast.FontStyle) toast.AlertDefinition {
	ret := _mock.Called(fontStyle)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 toast.AlertDefinition
	if returnFunc, ok := ret.Get(0).(func(toast.FontStyle) toast.AlertDefinition); ok {
		r0 = returnFunc(fontStyle)
	} else {
		r0 = ret.Get(0).(toast.AlertDefinition)
	}
	return r0
}

// MockAlertSpec_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockAlertSpec_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - fontStyle toast.FontStyle
func (_e *MockAlertSpec_Expecter) Resolve(fontStyle interface{}) *MockAlertSpec_Resolve_Call {
	return &MockAlertSpec_Resolve_Call{Call: _e.mock.On("Resolve", fontStyle)}
}

func (_c *MockAlertSpec_Resolve_Call) Run(run func(fontStyle toast.FontStyle)) *MockAlertSpec_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 toast.FontStyle
		if args[0] != nil {
			arg0 = args[0].(toast.FontStyle)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAlertSpec_Resolve_Call) Return(alertDefinition toast.AlertDefinition) *MockAlertSpec_Resolve_Call {
	_c.Call.Return(alertDefinition)
	return _c
}

func (_c *MockAlertSpec_Resolve_Call) RunAndReturn(run func(fontStyle toast.FontStyle) toast.AlertDefinition) *MockAlertSpec_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
